name: Deploy

on:
  push:
    branches: [ sandbox ]
  workflow_dispatch:

permissions:
  id-token: write     # REQUIRED for OIDC
  contents: read

jobs:
  test_aws_access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::606444776738:role/Teraform_Github_S3_Access
          aws-region: ap-south-1

      - name: Test AWS Access
        run: aws sts get-caller-identity

      - name: list s3 buckets
        run: aws s3 ls
      
      - name: List EC2 Instances
        run: aws ec2 describe-instances

  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    needs: test_aws_access

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::606444776738:role/Teraform_Github_S3_Access
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: Terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: Terraform
        run: terraform plan -out=plan.tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/sandbox'
        working-directory: Terraform
        run: terraform apply -auto-approve plan.tfplan